
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionChapter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionChapter
 * 
 */
export type QuestionChapterModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionChapterPayload>

export type AggregateQuestionChapter = {
  _count: QuestionChapterCountAggregateOutputType | null
  _avg: QuestionChapterAvgAggregateOutputType | null
  _sum: QuestionChapterSumAggregateOutputType | null
  _min: QuestionChapterMinAggregateOutputType | null
  _max: QuestionChapterMaxAggregateOutputType | null
}

export type QuestionChapterAvgAggregateOutputType = {
  externalId: number | null
  sortOrder: number | null
}

export type QuestionChapterSumAggregateOutputType = {
  externalId: number | null
  sortOrder: number | null
}

export type QuestionChapterMinAggregateOutputType = {
  id: string | null
  programId: string | null
  domain: $Enums.QuestionDomain | null
  externalId: number | null
  slug: string | null
  name: string | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionChapterMaxAggregateOutputType = {
  id: string | null
  programId: string | null
  domain: $Enums.QuestionDomain | null
  externalId: number | null
  slug: string | null
  name: string | null
  sortOrder: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionChapterCountAggregateOutputType = {
  id: number
  programId: number
  domain: number
  externalId: number
  slug: number
  name: number
  sortOrder: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QuestionChapterAvgAggregateInputType = {
  externalId?: true
  sortOrder?: true
}

export type QuestionChapterSumAggregateInputType = {
  externalId?: true
  sortOrder?: true
}

export type QuestionChapterMinAggregateInputType = {
  id?: true
  programId?: true
  domain?: true
  externalId?: true
  slug?: true
  name?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionChapterMaxAggregateInputType = {
  id?: true
  programId?: true
  domain?: true
  externalId?: true
  slug?: true
  name?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionChapterCountAggregateInputType = {
  id?: true
  programId?: true
  domain?: true
  externalId?: true
  slug?: true
  name?: true
  sortOrder?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QuestionChapterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionChapter to aggregate.
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionChapters to fetch.
   */
  orderBy?: Prisma.QuestionChapterOrderByWithRelationInput | Prisma.QuestionChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionChapters
  **/
  _count?: true | QuestionChapterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuestionChapterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuestionChapterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionChapterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionChapterMaxAggregateInputType
}

export type GetQuestionChapterAggregateType<T extends QuestionChapterAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionChapter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionChapter[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionChapter[P]>
}




export type QuestionChapterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionChapterWhereInput
  orderBy?: Prisma.QuestionChapterOrderByWithAggregationInput | Prisma.QuestionChapterOrderByWithAggregationInput[]
  by: Prisma.QuestionChapterScalarFieldEnum[] | Prisma.QuestionChapterScalarFieldEnum
  having?: Prisma.QuestionChapterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionChapterCountAggregateInputType | true
  _avg?: QuestionChapterAvgAggregateInputType
  _sum?: QuestionChapterSumAggregateInputType
  _min?: QuestionChapterMinAggregateInputType
  _max?: QuestionChapterMaxAggregateInputType
}

export type QuestionChapterGroupByOutputType = {
  id: string
  programId: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder: number
  createdAt: Date
  updatedAt: Date
  _count: QuestionChapterCountAggregateOutputType | null
  _avg: QuestionChapterAvgAggregateOutputType | null
  _sum: QuestionChapterSumAggregateOutputType | null
  _min: QuestionChapterMinAggregateOutputType | null
  _max: QuestionChapterMaxAggregateOutputType | null
}

export type GetQuestionChapterGroupByPayload<T extends QuestionChapterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionChapterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionChapterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionChapterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionChapterGroupByOutputType[P]>
      }
    >
  >



export type QuestionChapterWhereInput = {
  AND?: Prisma.QuestionChapterWhereInput | Prisma.QuestionChapterWhereInput[]
  OR?: Prisma.QuestionChapterWhereInput[]
  NOT?: Prisma.QuestionChapterWhereInput | Prisma.QuestionChapterWhereInput[]
  id?: Prisma.StringFilter<"QuestionChapter"> | string
  programId?: Prisma.StringFilter<"QuestionChapter"> | string
  domain?: Prisma.EnumQuestionDomainFilter<"QuestionChapter"> | $Enums.QuestionDomain
  externalId?: Prisma.IntFilter<"QuestionChapter"> | number
  slug?: Prisma.StringFilter<"QuestionChapter"> | string
  name?: Prisma.StringFilter<"QuestionChapter"> | string
  sortOrder?: Prisma.IntFilter<"QuestionChapter"> | number
  createdAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
  questions?: Prisma.QuestionListRelationFilter
}

export type QuestionChapterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  program?: Prisma.ProgramOrderByWithRelationInput
  questions?: Prisma.QuestionOrderByRelationAggregateInput
}

export type QuestionChapterWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  programId_domain_externalId?: Prisma.QuestionChapterProgramIdDomainExternalIdCompoundUniqueInput
  programId_domain_slug?: Prisma.QuestionChapterProgramIdDomainSlugCompoundUniqueInput
  id_programId_domain?: Prisma.QuestionChapterIdProgramIdDomainCompoundUniqueInput
  AND?: Prisma.QuestionChapterWhereInput | Prisma.QuestionChapterWhereInput[]
  OR?: Prisma.QuestionChapterWhereInput[]
  NOT?: Prisma.QuestionChapterWhereInput | Prisma.QuestionChapterWhereInput[]
  programId?: Prisma.StringFilter<"QuestionChapter"> | string
  domain?: Prisma.EnumQuestionDomainFilter<"QuestionChapter"> | $Enums.QuestionDomain
  externalId?: Prisma.IntFilter<"QuestionChapter"> | number
  slug?: Prisma.StringFilter<"QuestionChapter"> | string
  name?: Prisma.StringFilter<"QuestionChapter"> | string
  sortOrder?: Prisma.IntFilter<"QuestionChapter"> | number
  createdAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
  questions?: Prisma.QuestionListRelationFilter
}, "id" | "programId_domain_externalId" | "programId_domain_slug" | "id_programId_domain">

export type QuestionChapterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuestionChapterCountOrderByAggregateInput
  _avg?: Prisma.QuestionChapterAvgOrderByAggregateInput
  _max?: Prisma.QuestionChapterMaxOrderByAggregateInput
  _min?: Prisma.QuestionChapterMinOrderByAggregateInput
  _sum?: Prisma.QuestionChapterSumOrderByAggregateInput
}

export type QuestionChapterScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionChapterScalarWhereWithAggregatesInput | Prisma.QuestionChapterScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionChapterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionChapterScalarWhereWithAggregatesInput | Prisma.QuestionChapterScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionChapter"> | string
  programId?: Prisma.StringWithAggregatesFilter<"QuestionChapter"> | string
  domain?: Prisma.EnumQuestionDomainWithAggregatesFilter<"QuestionChapter"> | $Enums.QuestionDomain
  externalId?: Prisma.IntWithAggregatesFilter<"QuestionChapter"> | number
  slug?: Prisma.StringWithAggregatesFilter<"QuestionChapter"> | string
  name?: Prisma.StringWithAggregatesFilter<"QuestionChapter"> | string
  sortOrder?: Prisma.IntWithAggregatesFilter<"QuestionChapter"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionChapter"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionChapter"> | Date | string
}

export type QuestionChapterCreateInput = {
  id?: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  program: Prisma.ProgramCreateNestedOneWithoutChaptersInput
  questions?: Prisma.QuestionCreateNestedManyWithoutChapterInput
}

export type QuestionChapterUncheckedCreateInput = {
  id?: string
  programId: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutChapterInput
}

export type QuestionChapterUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  program?: Prisma.ProgramUpdateOneRequiredWithoutChaptersNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutChapterNestedInput
}

export type QuestionChapterUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutChapterNestedInput
}

export type QuestionChapterCreateManyInput = {
  id?: string
  programId: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionChapterUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionChapterUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionChapterListRelationFilter = {
  every?: Prisma.QuestionChapterWhereInput
  some?: Prisma.QuestionChapterWhereInput
  none?: Prisma.QuestionChapterWhereInput
}

export type QuestionChapterOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionChapterProgramIdDomainExternalIdCompoundUniqueInput = {
  programId: string
  domain: $Enums.QuestionDomain
  externalId: number
}

export type QuestionChapterProgramIdDomainSlugCompoundUniqueInput = {
  programId: string
  domain: $Enums.QuestionDomain
  slug: string
}

export type QuestionChapterIdProgramIdDomainCompoundUniqueInput = {
  id: string
  programId: string
  domain: $Enums.QuestionDomain
}

export type QuestionChapterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionChapterAvgOrderByAggregateInput = {
  externalId?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type QuestionChapterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionChapterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  domain?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionChapterSumOrderByAggregateInput = {
  externalId?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type QuestionChapterScalarRelationFilter = {
  is?: Prisma.QuestionChapterWhereInput
  isNot?: Prisma.QuestionChapterWhereInput
}

export type QuestionChapterCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput> | Prisma.QuestionChapterCreateWithoutProgramInput[] | Prisma.QuestionChapterUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutProgramInput | Prisma.QuestionChapterCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.QuestionChapterCreateManyProgramInputEnvelope
  connect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
}

export type QuestionChapterUncheckedCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput> | Prisma.QuestionChapterCreateWithoutProgramInput[] | Prisma.QuestionChapterUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutProgramInput | Prisma.QuestionChapterCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.QuestionChapterCreateManyProgramInputEnvelope
  connect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
}

export type QuestionChapterUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput> | Prisma.QuestionChapterCreateWithoutProgramInput[] | Prisma.QuestionChapterUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutProgramInput | Prisma.QuestionChapterCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.QuestionChapterUpsertWithWhereUniqueWithoutProgramInput | Prisma.QuestionChapterUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.QuestionChapterCreateManyProgramInputEnvelope
  set?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  disconnect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  delete?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  connect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  update?: Prisma.QuestionChapterUpdateWithWhereUniqueWithoutProgramInput | Prisma.QuestionChapterUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.QuestionChapterUpdateManyWithWhereWithoutProgramInput | Prisma.QuestionChapterUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.QuestionChapterScalarWhereInput | Prisma.QuestionChapterScalarWhereInput[]
}

export type QuestionChapterUncheckedUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput> | Prisma.QuestionChapterCreateWithoutProgramInput[] | Prisma.QuestionChapterUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutProgramInput | Prisma.QuestionChapterCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.QuestionChapterUpsertWithWhereUniqueWithoutProgramInput | Prisma.QuestionChapterUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.QuestionChapterCreateManyProgramInputEnvelope
  set?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  disconnect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  delete?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  connect?: Prisma.QuestionChapterWhereUniqueInput | Prisma.QuestionChapterWhereUniqueInput[]
  update?: Prisma.QuestionChapterUpdateWithWhereUniqueWithoutProgramInput | Prisma.QuestionChapterUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.QuestionChapterUpdateManyWithWhereWithoutProgramInput | Prisma.QuestionChapterUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.QuestionChapterScalarWhereInput | Prisma.QuestionChapterScalarWhereInput[]
}

export type EnumQuestionDomainFieldUpdateOperationsInput = {
  set?: $Enums.QuestionDomain
}

export type QuestionChapterCreateNestedOneWithoutQuestionsInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutQuestionsInput
  connect?: Prisma.QuestionChapterWhereUniqueInput
}

export type QuestionChapterUpdateOneRequiredWithoutQuestionsNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionChapterCreateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.QuestionChapterCreateOrConnectWithoutQuestionsInput
  upsert?: Prisma.QuestionChapterUpsertWithoutQuestionsInput
  connect?: Prisma.QuestionChapterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.QuestionChapterUpdateToOneWithWhereWithoutQuestionsInput, Prisma.QuestionChapterUpdateWithoutQuestionsInput>, Prisma.QuestionChapterUncheckedUpdateWithoutQuestionsInput>
}

export type QuestionChapterCreateWithoutProgramInput = {
  id?: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionCreateNestedManyWithoutChapterInput
}

export type QuestionChapterUncheckedCreateWithoutProgramInput = {
  id?: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutChapterInput
}

export type QuestionChapterCreateOrConnectWithoutProgramInput = {
  where: Prisma.QuestionChapterWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput>
}

export type QuestionChapterCreateManyProgramInputEnvelope = {
  data: Prisma.QuestionChapterCreateManyProgramInput | Prisma.QuestionChapterCreateManyProgramInput[]
  skipDuplicates?: boolean
}

export type QuestionChapterUpsertWithWhereUniqueWithoutProgramInput = {
  where: Prisma.QuestionChapterWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionChapterUpdateWithoutProgramInput, Prisma.QuestionChapterUncheckedUpdateWithoutProgramInput>
  create: Prisma.XOR<Prisma.QuestionChapterCreateWithoutProgramInput, Prisma.QuestionChapterUncheckedCreateWithoutProgramInput>
}

export type QuestionChapterUpdateWithWhereUniqueWithoutProgramInput = {
  where: Prisma.QuestionChapterWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionChapterUpdateWithoutProgramInput, Prisma.QuestionChapterUncheckedUpdateWithoutProgramInput>
}

export type QuestionChapterUpdateManyWithWhereWithoutProgramInput = {
  where: Prisma.QuestionChapterScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionChapterUpdateManyMutationInput, Prisma.QuestionChapterUncheckedUpdateManyWithoutProgramInput>
}

export type QuestionChapterScalarWhereInput = {
  AND?: Prisma.QuestionChapterScalarWhereInput | Prisma.QuestionChapterScalarWhereInput[]
  OR?: Prisma.QuestionChapterScalarWhereInput[]
  NOT?: Prisma.QuestionChapterScalarWhereInput | Prisma.QuestionChapterScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionChapter"> | string
  programId?: Prisma.StringFilter<"QuestionChapter"> | string
  domain?: Prisma.EnumQuestionDomainFilter<"QuestionChapter"> | $Enums.QuestionDomain
  externalId?: Prisma.IntFilter<"QuestionChapter"> | number
  slug?: Prisma.StringFilter<"QuestionChapter"> | string
  name?: Prisma.StringFilter<"QuestionChapter"> | string
  sortOrder?: Prisma.IntFilter<"QuestionChapter"> | number
  createdAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionChapter"> | Date | string
}

export type QuestionChapterCreateWithoutQuestionsInput = {
  id?: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  program: Prisma.ProgramCreateNestedOneWithoutChaptersInput
}

export type QuestionChapterUncheckedCreateWithoutQuestionsInput = {
  id?: string
  programId: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionChapterCreateOrConnectWithoutQuestionsInput = {
  where: Prisma.QuestionChapterWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionChapterCreateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedCreateWithoutQuestionsInput>
}

export type QuestionChapterUpsertWithoutQuestionsInput = {
  update: Prisma.XOR<Prisma.QuestionChapterUpdateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedUpdateWithoutQuestionsInput>
  create: Prisma.XOR<Prisma.QuestionChapterCreateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedCreateWithoutQuestionsInput>
  where?: Prisma.QuestionChapterWhereInput
}

export type QuestionChapterUpdateToOneWithWhereWithoutQuestionsInput = {
  where?: Prisma.QuestionChapterWhereInput
  data: Prisma.XOR<Prisma.QuestionChapterUpdateWithoutQuestionsInput, Prisma.QuestionChapterUncheckedUpdateWithoutQuestionsInput>
}

export type QuestionChapterUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  program?: Prisma.ProgramUpdateOneRequiredWithoutChaptersNestedInput
}

export type QuestionChapterUncheckedUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionChapterCreateManyProgramInput = {
  id?: string
  domain: $Enums.QuestionDomain
  externalId: number
  slug: string
  name: string
  sortOrder?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionChapterUpdateWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUpdateManyWithoutChapterNestedInput
}

export type QuestionChapterUncheckedUpdateWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutChapterNestedInput
}

export type QuestionChapterUncheckedUpdateManyWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain?: Prisma.EnumQuestionDomainFieldUpdateOperationsInput | $Enums.QuestionDomain
  externalId?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type QuestionChapterCountOutputType
 */

export type QuestionChapterCountOutputType = {
  questions: number
}

export type QuestionChapterCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  questions?: boolean | QuestionChapterCountOutputTypeCountQuestionsArgs
}

/**
 * QuestionChapterCountOutputType without action
 */
export type QuestionChapterCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapterCountOutputType
   */
  select?: Prisma.QuestionChapterCountOutputTypeSelect<ExtArgs> | null
}

/**
 * QuestionChapterCountOutputType without action
 */
export type QuestionChapterCountOutputTypeCountQuestionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionWhereInput
}


export type QuestionChapterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  domain?: boolean
  externalId?: boolean
  slug?: boolean
  name?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  questions?: boolean | Prisma.QuestionChapter$questionsArgs<ExtArgs>
  _count?: boolean | Prisma.QuestionChapterCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionChapter"]>

export type QuestionChapterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  domain?: boolean
  externalId?: boolean
  slug?: boolean
  name?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionChapter"]>

export type QuestionChapterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  domain?: boolean
  externalId?: boolean
  slug?: boolean
  name?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionChapter"]>

export type QuestionChapterSelectScalar = {
  id?: boolean
  programId?: boolean
  domain?: boolean
  externalId?: boolean
  slug?: boolean
  name?: boolean
  sortOrder?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QuestionChapterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "programId" | "domain" | "externalId" | "slug" | "name" | "sortOrder" | "createdAt" | "updatedAt", ExtArgs["result"]["questionChapter"]>
export type QuestionChapterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  questions?: boolean | Prisma.QuestionChapter$questionsArgs<ExtArgs>
  _count?: boolean | Prisma.QuestionChapterCountOutputTypeDefaultArgs<ExtArgs>
}
export type QuestionChapterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}
export type QuestionChapterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}

export type $QuestionChapterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionChapter"
  objects: {
    program: Prisma.$ProgramPayload<ExtArgs>
    questions: Prisma.$QuestionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    programId: string
    domain: $Enums.QuestionDomain
    externalId: number
    slug: string
    name: string
    sortOrder: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["questionChapter"]>
  composites: {}
}

export type QuestionChapterGetPayload<S extends boolean | null | undefined | QuestionChapterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload, S>

export type QuestionChapterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionChapterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionChapterCountAggregateInputType | true
  }

export interface QuestionChapterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionChapter'], meta: { name: 'QuestionChapter' } }
  /**
   * Find zero or one QuestionChapter that matches the filter.
   * @param {QuestionChapterFindUniqueArgs} args - Arguments to find a QuestionChapter
   * @example
   * // Get one QuestionChapter
   * const questionChapter = await prisma.questionChapter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionChapterFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionChapterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionChapter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionChapterFindUniqueOrThrowArgs} args - Arguments to find a QuestionChapter
   * @example
   * // Get one QuestionChapter
   * const questionChapter = await prisma.questionChapter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionChapterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionChapterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionChapter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterFindFirstArgs} args - Arguments to find a QuestionChapter
   * @example
   * // Get one QuestionChapter
   * const questionChapter = await prisma.questionChapter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionChapterFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionChapterFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionChapter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterFindFirstOrThrowArgs} args - Arguments to find a QuestionChapter
   * @example
   * // Get one QuestionChapter
   * const questionChapter = await prisma.questionChapter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionChapterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionChapterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionChapters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionChapters
   * const questionChapters = await prisma.questionChapter.findMany()
   * 
   * // Get first 10 QuestionChapters
   * const questionChapters = await prisma.questionChapter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionChapterWithIdOnly = await prisma.questionChapter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionChapterFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionChapterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionChapter.
   * @param {QuestionChapterCreateArgs} args - Arguments to create a QuestionChapter.
   * @example
   * // Create one QuestionChapter
   * const QuestionChapter = await prisma.questionChapter.create({
   *   data: {
   *     // ... data to create a QuestionChapter
   *   }
   * })
   * 
   */
  create<T extends QuestionChapterCreateArgs>(args: Prisma.SelectSubset<T, QuestionChapterCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionChapters.
   * @param {QuestionChapterCreateManyArgs} args - Arguments to create many QuestionChapters.
   * @example
   * // Create many QuestionChapters
   * const questionChapter = await prisma.questionChapter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionChapterCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionChapterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionChapters and returns the data saved in the database.
   * @param {QuestionChapterCreateManyAndReturnArgs} args - Arguments to create many QuestionChapters.
   * @example
   * // Create many QuestionChapters
   * const questionChapter = await prisma.questionChapter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionChapters and only return the `id`
   * const questionChapterWithIdOnly = await prisma.questionChapter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionChapterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionChapterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionChapter.
   * @param {QuestionChapterDeleteArgs} args - Arguments to delete one QuestionChapter.
   * @example
   * // Delete one QuestionChapter
   * const QuestionChapter = await prisma.questionChapter.delete({
   *   where: {
   *     // ... filter to delete one QuestionChapter
   *   }
   * })
   * 
   */
  delete<T extends QuestionChapterDeleteArgs>(args: Prisma.SelectSubset<T, QuestionChapterDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionChapter.
   * @param {QuestionChapterUpdateArgs} args - Arguments to update one QuestionChapter.
   * @example
   * // Update one QuestionChapter
   * const questionChapter = await prisma.questionChapter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionChapterUpdateArgs>(args: Prisma.SelectSubset<T, QuestionChapterUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionChapters.
   * @param {QuestionChapterDeleteManyArgs} args - Arguments to filter QuestionChapters to delete.
   * @example
   * // Delete a few QuestionChapters
   * const { count } = await prisma.questionChapter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionChapterDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionChapterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionChapters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionChapters
   * const questionChapter = await prisma.questionChapter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionChapterUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionChapterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionChapters and returns the data updated in the database.
   * @param {QuestionChapterUpdateManyAndReturnArgs} args - Arguments to update many QuestionChapters.
   * @example
   * // Update many QuestionChapters
   * const questionChapter = await prisma.questionChapter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionChapters and only return the `id`
   * const questionChapterWithIdOnly = await prisma.questionChapter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionChapterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionChapterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionChapter.
   * @param {QuestionChapterUpsertArgs} args - Arguments to update or create a QuestionChapter.
   * @example
   * // Update or create a QuestionChapter
   * const questionChapter = await prisma.questionChapter.upsert({
   *   create: {
   *     // ... data to create a QuestionChapter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionChapter we want to update
   *   }
   * })
   */
  upsert<T extends QuestionChapterUpsertArgs>(args: Prisma.SelectSubset<T, QuestionChapterUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionChapterClient<runtime.Types.Result.GetResult<Prisma.$QuestionChapterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionChapters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterCountArgs} args - Arguments to filter QuestionChapters to count.
   * @example
   * // Count the number of QuestionChapters
   * const count = await prisma.questionChapter.count({
   *   where: {
   *     // ... the filter for the QuestionChapters we want to count
   *   }
   * })
  **/
  count<T extends QuestionChapterCountArgs>(
    args?: Prisma.Subset<T, QuestionChapterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionChapterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionChapter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionChapterAggregateArgs>(args: Prisma.Subset<T, QuestionChapterAggregateArgs>): Prisma.PrismaPromise<GetQuestionChapterAggregateType<T>>

  /**
   * Group by QuestionChapter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionChapterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionChapterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionChapterGroupByArgs['orderBy'] }
      : { orderBy?: QuestionChapterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionChapterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionChapterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionChapter model
 */
readonly fields: QuestionChapterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionChapter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionChapterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  program<T extends Prisma.ProgramDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgramDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgramClient<runtime.Types.Result.GetResult<Prisma.$ProgramPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  questions<T extends Prisma.QuestionChapter$questionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionChapter$questionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionChapter model
 */
export interface QuestionChapterFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionChapter", 'String'>
  readonly programId: Prisma.FieldRef<"QuestionChapter", 'String'>
  readonly domain: Prisma.FieldRef<"QuestionChapter", 'QuestionDomain'>
  readonly externalId: Prisma.FieldRef<"QuestionChapter", 'Int'>
  readonly slug: Prisma.FieldRef<"QuestionChapter", 'String'>
  readonly name: Prisma.FieldRef<"QuestionChapter", 'String'>
  readonly sortOrder: Prisma.FieldRef<"QuestionChapter", 'Int'>
  readonly createdAt: Prisma.FieldRef<"QuestionChapter", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuestionChapter", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionChapter findUnique
 */
export type QuestionChapterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter, which QuestionChapter to fetch.
   */
  where: Prisma.QuestionChapterWhereUniqueInput
}

/**
 * QuestionChapter findUniqueOrThrow
 */
export type QuestionChapterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter, which QuestionChapter to fetch.
   */
  where: Prisma.QuestionChapterWhereUniqueInput
}

/**
 * QuestionChapter findFirst
 */
export type QuestionChapterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter, which QuestionChapter to fetch.
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionChapters to fetch.
   */
  orderBy?: Prisma.QuestionChapterOrderByWithRelationInput | Prisma.QuestionChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionChapters.
   */
  cursor?: Prisma.QuestionChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionChapters.
   */
  distinct?: Prisma.QuestionChapterScalarFieldEnum | Prisma.QuestionChapterScalarFieldEnum[]
}

/**
 * QuestionChapter findFirstOrThrow
 */
export type QuestionChapterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter, which QuestionChapter to fetch.
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionChapters to fetch.
   */
  orderBy?: Prisma.QuestionChapterOrderByWithRelationInput | Prisma.QuestionChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionChapters.
   */
  cursor?: Prisma.QuestionChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionChapters.
   */
  distinct?: Prisma.QuestionChapterScalarFieldEnum | Prisma.QuestionChapterScalarFieldEnum[]
}

/**
 * QuestionChapter findMany
 */
export type QuestionChapterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter, which QuestionChapters to fetch.
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionChapters to fetch.
   */
  orderBy?: Prisma.QuestionChapterOrderByWithRelationInput | Prisma.QuestionChapterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionChapters.
   */
  cursor?: Prisma.QuestionChapterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionChapters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionChapters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionChapters.
   */
  distinct?: Prisma.QuestionChapterScalarFieldEnum | Prisma.QuestionChapterScalarFieldEnum[]
}

/**
 * QuestionChapter create
 */
export type QuestionChapterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionChapter.
   */
  data: Prisma.XOR<Prisma.QuestionChapterCreateInput, Prisma.QuestionChapterUncheckedCreateInput>
}

/**
 * QuestionChapter createMany
 */
export type QuestionChapterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionChapters.
   */
  data: Prisma.QuestionChapterCreateManyInput | Prisma.QuestionChapterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuestionChapter createManyAndReturn
 */
export type QuestionChapterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionChapters.
   */
  data: Prisma.QuestionChapterCreateManyInput | Prisma.QuestionChapterCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionChapter update
 */
export type QuestionChapterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionChapter.
   */
  data: Prisma.XOR<Prisma.QuestionChapterUpdateInput, Prisma.QuestionChapterUncheckedUpdateInput>
  /**
   * Choose, which QuestionChapter to update.
   */
  where: Prisma.QuestionChapterWhereUniqueInput
}

/**
 * QuestionChapter updateMany
 */
export type QuestionChapterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionChapters.
   */
  data: Prisma.XOR<Prisma.QuestionChapterUpdateManyMutationInput, Prisma.QuestionChapterUncheckedUpdateManyInput>
  /**
   * Filter which QuestionChapters to update
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * Limit how many QuestionChapters to update.
   */
  limit?: number
}

/**
 * QuestionChapter updateManyAndReturn
 */
export type QuestionChapterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * The data used to update QuestionChapters.
   */
  data: Prisma.XOR<Prisma.QuestionChapterUpdateManyMutationInput, Prisma.QuestionChapterUncheckedUpdateManyInput>
  /**
   * Filter which QuestionChapters to update
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * Limit how many QuestionChapters to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionChapter upsert
 */
export type QuestionChapterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionChapter to update in case it exists.
   */
  where: Prisma.QuestionChapterWhereUniqueInput
  /**
   * In case the QuestionChapter found by the `where` argument doesn't exist, create a new QuestionChapter with this data.
   */
  create: Prisma.XOR<Prisma.QuestionChapterCreateInput, Prisma.QuestionChapterUncheckedCreateInput>
  /**
   * In case the QuestionChapter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionChapterUpdateInput, Prisma.QuestionChapterUncheckedUpdateInput>
}

/**
 * QuestionChapter delete
 */
export type QuestionChapterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
  /**
   * Filter which QuestionChapter to delete.
   */
  where: Prisma.QuestionChapterWhereUniqueInput
}

/**
 * QuestionChapter deleteMany
 */
export type QuestionChapterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionChapters to delete
   */
  where?: Prisma.QuestionChapterWhereInput
  /**
   * Limit how many QuestionChapters to delete.
   */
  limit?: number
}

/**
 * QuestionChapter.questions
 */
export type QuestionChapter$questionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Question
   */
  select?: Prisma.QuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Question
   */
  omit?: Prisma.QuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionInclude<ExtArgs> | null
  where?: Prisma.QuestionWhereInput
  orderBy?: Prisma.QuestionOrderByWithRelationInput | Prisma.QuestionOrderByWithRelationInput[]
  cursor?: Prisma.QuestionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuestionScalarFieldEnum | Prisma.QuestionScalarFieldEnum[]
}

/**
 * QuestionChapter without action
 */
export type QuestionChapterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionChapter
   */
  select?: Prisma.QuestionChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionChapter
   */
  omit?: Prisma.QuestionChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionChapterInclude<ExtArgs> | null
}
