
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionFigure` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionFigure
 * 
 */
export type QuestionFigureModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionFigurePayload>

export type AggregateQuestionFigure = {
  _count: QuestionFigureCountAggregateOutputType | null
  _avg: QuestionFigureAvgAggregateOutputType | null
  _sum: QuestionFigureSumAggregateOutputType | null
  _min: QuestionFigureMinAggregateOutputType | null
  _max: QuestionFigureMaxAggregateOutputType | null
}

export type QuestionFigureAvgAggregateOutputType = {
  byteSize: number | null
}

export type QuestionFigureSumAggregateOutputType = {
  byteSize: number | null
}

export type QuestionFigureMinAggregateOutputType = {
  id: string | null
  programId: string | null
  path: string | null
  fileName: string | null
  svg: string | null
  byteSize: number | null
  checksum: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionFigureMaxAggregateOutputType = {
  id: string | null
  programId: string | null
  path: string | null
  fileName: string | null
  svg: string | null
  byteSize: number | null
  checksum: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QuestionFigureCountAggregateOutputType = {
  id: number
  programId: number
  path: number
  fileName: number
  svg: number
  byteSize: number
  checksum: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QuestionFigureAvgAggregateInputType = {
  byteSize?: true
}

export type QuestionFigureSumAggregateInputType = {
  byteSize?: true
}

export type QuestionFigureMinAggregateInputType = {
  id?: true
  programId?: true
  path?: true
  fileName?: true
  svg?: true
  byteSize?: true
  checksum?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionFigureMaxAggregateInputType = {
  id?: true
  programId?: true
  path?: true
  fileName?: true
  svg?: true
  byteSize?: true
  checksum?: true
  createdAt?: true
  updatedAt?: true
}

export type QuestionFigureCountAggregateInputType = {
  id?: true
  programId?: true
  path?: true
  fileName?: true
  svg?: true
  byteSize?: true
  checksum?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QuestionFigureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionFigure to aggregate.
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionFigures to fetch.
   */
  orderBy?: Prisma.QuestionFigureOrderByWithRelationInput | Prisma.QuestionFigureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionFigureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionFigures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionFigures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionFigures
  **/
  _count?: true | QuestionFigureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuestionFigureAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuestionFigureSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionFigureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionFigureMaxAggregateInputType
}

export type GetQuestionFigureAggregateType<T extends QuestionFigureAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionFigure]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionFigure[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionFigure[P]>
}




export type QuestionFigureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionFigureWhereInput
  orderBy?: Prisma.QuestionFigureOrderByWithAggregationInput | Prisma.QuestionFigureOrderByWithAggregationInput[]
  by: Prisma.QuestionFigureScalarFieldEnum[] | Prisma.QuestionFigureScalarFieldEnum
  having?: Prisma.QuestionFigureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionFigureCountAggregateInputType | true
  _avg?: QuestionFigureAvgAggregateInputType
  _sum?: QuestionFigureSumAggregateInputType
  _min?: QuestionFigureMinAggregateInputType
  _max?: QuestionFigureMaxAggregateInputType
}

export type QuestionFigureGroupByOutputType = {
  id: string
  programId: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt: Date
  updatedAt: Date
  _count: QuestionFigureCountAggregateOutputType | null
  _avg: QuestionFigureAvgAggregateOutputType | null
  _sum: QuestionFigureSumAggregateOutputType | null
  _min: QuestionFigureMinAggregateOutputType | null
  _max: QuestionFigureMaxAggregateOutputType | null
}

export type GetQuestionFigureGroupByPayload<T extends QuestionFigureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionFigureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionFigureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionFigureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionFigureGroupByOutputType[P]>
      }
    >
  >



export type QuestionFigureWhereInput = {
  AND?: Prisma.QuestionFigureWhereInput | Prisma.QuestionFigureWhereInput[]
  OR?: Prisma.QuestionFigureWhereInput[]
  NOT?: Prisma.QuestionFigureWhereInput | Prisma.QuestionFigureWhereInput[]
  id?: Prisma.StringFilter<"QuestionFigure"> | string
  programId?: Prisma.StringFilter<"QuestionFigure"> | string
  path?: Prisma.StringFilter<"QuestionFigure"> | string
  fileName?: Prisma.StringFilter<"QuestionFigure"> | string
  svg?: Prisma.StringFilter<"QuestionFigure"> | string
  byteSize?: Prisma.IntFilter<"QuestionFigure"> | number
  checksum?: Prisma.StringFilter<"QuestionFigure"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
}

export type QuestionFigureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  svg?: Prisma.SortOrder
  byteSize?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  program?: Prisma.ProgramOrderByWithRelationInput
}

export type QuestionFigureWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  programId_path?: Prisma.QuestionFigureProgramIdPathCompoundUniqueInput
  AND?: Prisma.QuestionFigureWhereInput | Prisma.QuestionFigureWhereInput[]
  OR?: Prisma.QuestionFigureWhereInput[]
  NOT?: Prisma.QuestionFigureWhereInput | Prisma.QuestionFigureWhereInput[]
  programId?: Prisma.StringFilter<"QuestionFigure"> | string
  path?: Prisma.StringFilter<"QuestionFigure"> | string
  fileName?: Prisma.StringFilter<"QuestionFigure"> | string
  svg?: Prisma.StringFilter<"QuestionFigure"> | string
  byteSize?: Prisma.IntFilter<"QuestionFigure"> | number
  checksum?: Prisma.StringFilter<"QuestionFigure"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
}, "id" | "programId_path">

export type QuestionFigureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  svg?: Prisma.SortOrder
  byteSize?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QuestionFigureCountOrderByAggregateInput
  _avg?: Prisma.QuestionFigureAvgOrderByAggregateInput
  _max?: Prisma.QuestionFigureMaxOrderByAggregateInput
  _min?: Prisma.QuestionFigureMinOrderByAggregateInput
  _sum?: Prisma.QuestionFigureSumOrderByAggregateInput
}

export type QuestionFigureScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionFigureScalarWhereWithAggregatesInput | Prisma.QuestionFigureScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionFigureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionFigureScalarWhereWithAggregatesInput | Prisma.QuestionFigureScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  programId?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  path?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  svg?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  byteSize?: Prisma.IntWithAggregatesFilter<"QuestionFigure"> | number
  checksum?: Prisma.StringWithAggregatesFilter<"QuestionFigure"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionFigure"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionFigure"> | Date | string
}

export type QuestionFigureCreateInput = {
  id?: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
  program: Prisma.ProgramCreateNestedOneWithoutFiguresInput
}

export type QuestionFigureUncheckedCreateInput = {
  id?: string
  programId: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionFigureUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  program?: Prisma.ProgramUpdateOneRequiredWithoutFiguresNestedInput
}

export type QuestionFigureUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionFigureCreateManyInput = {
  id?: string
  programId: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionFigureUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionFigureUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  programId?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionFigureListRelationFilter = {
  every?: Prisma.QuestionFigureWhereInput
  some?: Prisma.QuestionFigureWhereInput
  none?: Prisma.QuestionFigureWhereInput
}

export type QuestionFigureOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionFigureProgramIdPathCompoundUniqueInput = {
  programId: string
  path: string
}

export type QuestionFigureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  svg?: Prisma.SortOrder
  byteSize?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionFigureAvgOrderByAggregateInput = {
  byteSize?: Prisma.SortOrder
}

export type QuestionFigureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  svg?: Prisma.SortOrder
  byteSize?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionFigureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  path?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  svg?: Prisma.SortOrder
  byteSize?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QuestionFigureSumOrderByAggregateInput = {
  byteSize?: Prisma.SortOrder
}

export type QuestionFigureCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput> | Prisma.QuestionFigureCreateWithoutProgramInput[] | Prisma.QuestionFigureUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionFigureCreateOrConnectWithoutProgramInput | Prisma.QuestionFigureCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.QuestionFigureCreateManyProgramInputEnvelope
  connect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
}

export type QuestionFigureUncheckedCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput> | Prisma.QuestionFigureCreateWithoutProgramInput[] | Prisma.QuestionFigureUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionFigureCreateOrConnectWithoutProgramInput | Prisma.QuestionFigureCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.QuestionFigureCreateManyProgramInputEnvelope
  connect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
}

export type QuestionFigureUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput> | Prisma.QuestionFigureCreateWithoutProgramInput[] | Prisma.QuestionFigureUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionFigureCreateOrConnectWithoutProgramInput | Prisma.QuestionFigureCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.QuestionFigureUpsertWithWhereUniqueWithoutProgramInput | Prisma.QuestionFigureUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.QuestionFigureCreateManyProgramInputEnvelope
  set?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  disconnect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  delete?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  connect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  update?: Prisma.QuestionFigureUpdateWithWhereUniqueWithoutProgramInput | Prisma.QuestionFigureUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.QuestionFigureUpdateManyWithWhereWithoutProgramInput | Prisma.QuestionFigureUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.QuestionFigureScalarWhereInput | Prisma.QuestionFigureScalarWhereInput[]
}

export type QuestionFigureUncheckedUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput> | Prisma.QuestionFigureCreateWithoutProgramInput[] | Prisma.QuestionFigureUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.QuestionFigureCreateOrConnectWithoutProgramInput | Prisma.QuestionFigureCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.QuestionFigureUpsertWithWhereUniqueWithoutProgramInput | Prisma.QuestionFigureUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.QuestionFigureCreateManyProgramInputEnvelope
  set?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  disconnect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  delete?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  connect?: Prisma.QuestionFigureWhereUniqueInput | Prisma.QuestionFigureWhereUniqueInput[]
  update?: Prisma.QuestionFigureUpdateWithWhereUniqueWithoutProgramInput | Prisma.QuestionFigureUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.QuestionFigureUpdateManyWithWhereWithoutProgramInput | Prisma.QuestionFigureUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.QuestionFigureScalarWhereInput | Prisma.QuestionFigureScalarWhereInput[]
}

export type QuestionFigureCreateWithoutProgramInput = {
  id?: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionFigureUncheckedCreateWithoutProgramInput = {
  id?: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionFigureCreateOrConnectWithoutProgramInput = {
  where: Prisma.QuestionFigureWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput>
}

export type QuestionFigureCreateManyProgramInputEnvelope = {
  data: Prisma.QuestionFigureCreateManyProgramInput | Prisma.QuestionFigureCreateManyProgramInput[]
  skipDuplicates?: boolean
}

export type QuestionFigureUpsertWithWhereUniqueWithoutProgramInput = {
  where: Prisma.QuestionFigureWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionFigureUpdateWithoutProgramInput, Prisma.QuestionFigureUncheckedUpdateWithoutProgramInput>
  create: Prisma.XOR<Prisma.QuestionFigureCreateWithoutProgramInput, Prisma.QuestionFigureUncheckedCreateWithoutProgramInput>
}

export type QuestionFigureUpdateWithWhereUniqueWithoutProgramInput = {
  where: Prisma.QuestionFigureWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionFigureUpdateWithoutProgramInput, Prisma.QuestionFigureUncheckedUpdateWithoutProgramInput>
}

export type QuestionFigureUpdateManyWithWhereWithoutProgramInput = {
  where: Prisma.QuestionFigureScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionFigureUpdateManyMutationInput, Prisma.QuestionFigureUncheckedUpdateManyWithoutProgramInput>
}

export type QuestionFigureScalarWhereInput = {
  AND?: Prisma.QuestionFigureScalarWhereInput | Prisma.QuestionFigureScalarWhereInput[]
  OR?: Prisma.QuestionFigureScalarWhereInput[]
  NOT?: Prisma.QuestionFigureScalarWhereInput | Prisma.QuestionFigureScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionFigure"> | string
  programId?: Prisma.StringFilter<"QuestionFigure"> | string
  path?: Prisma.StringFilter<"QuestionFigure"> | string
  fileName?: Prisma.StringFilter<"QuestionFigure"> | string
  svg?: Prisma.StringFilter<"QuestionFigure"> | string
  byteSize?: Prisma.IntFilter<"QuestionFigure"> | number
  checksum?: Prisma.StringFilter<"QuestionFigure"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QuestionFigure"> | Date | string
}

export type QuestionFigureCreateManyProgramInput = {
  id?: string
  path: string
  fileName: string
  svg: string
  byteSize: number
  checksum: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QuestionFigureUpdateWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionFigureUncheckedUpdateWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionFigureUncheckedUpdateManyWithoutProgramInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  svg?: Prisma.StringFieldUpdateOperationsInput | string
  byteSize?: Prisma.IntFieldUpdateOperationsInput | number
  checksum?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuestionFigureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  path?: boolean
  fileName?: boolean
  svg?: boolean
  byteSize?: boolean
  checksum?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionFigure"]>

export type QuestionFigureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  path?: boolean
  fileName?: boolean
  svg?: boolean
  byteSize?: boolean
  checksum?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionFigure"]>

export type QuestionFigureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  path?: boolean
  fileName?: boolean
  svg?: boolean
  byteSize?: boolean
  checksum?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionFigure"]>

export type QuestionFigureSelectScalar = {
  id?: boolean
  programId?: boolean
  path?: boolean
  fileName?: boolean
  svg?: boolean
  byteSize?: boolean
  checksum?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QuestionFigureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "programId" | "path" | "fileName" | "svg" | "byteSize" | "checksum" | "createdAt" | "updatedAt", ExtArgs["result"]["questionFigure"]>
export type QuestionFigureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}
export type QuestionFigureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}
export type QuestionFigureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
}

export type $QuestionFigurePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionFigure"
  objects: {
    program: Prisma.$ProgramPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    programId: string
    path: string
    fileName: string
    svg: string
    byteSize: number
    checksum: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["questionFigure"]>
  composites: {}
}

export type QuestionFigureGetPayload<S extends boolean | null | undefined | QuestionFigureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload, S>

export type QuestionFigureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionFigureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionFigureCountAggregateInputType | true
  }

export interface QuestionFigureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionFigure'], meta: { name: 'QuestionFigure' } }
  /**
   * Find zero or one QuestionFigure that matches the filter.
   * @param {QuestionFigureFindUniqueArgs} args - Arguments to find a QuestionFigure
   * @example
   * // Get one QuestionFigure
   * const questionFigure = await prisma.questionFigure.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionFigureFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionFigureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionFigure that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionFigureFindUniqueOrThrowArgs} args - Arguments to find a QuestionFigure
   * @example
   * // Get one QuestionFigure
   * const questionFigure = await prisma.questionFigure.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionFigureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionFigureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionFigure that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureFindFirstArgs} args - Arguments to find a QuestionFigure
   * @example
   * // Get one QuestionFigure
   * const questionFigure = await prisma.questionFigure.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionFigureFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionFigureFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionFigure that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureFindFirstOrThrowArgs} args - Arguments to find a QuestionFigure
   * @example
   * // Get one QuestionFigure
   * const questionFigure = await prisma.questionFigure.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionFigureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionFigureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionFigures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionFigures
   * const questionFigures = await prisma.questionFigure.findMany()
   * 
   * // Get first 10 QuestionFigures
   * const questionFigures = await prisma.questionFigure.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionFigureWithIdOnly = await prisma.questionFigure.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionFigureFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionFigureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionFigure.
   * @param {QuestionFigureCreateArgs} args - Arguments to create a QuestionFigure.
   * @example
   * // Create one QuestionFigure
   * const QuestionFigure = await prisma.questionFigure.create({
   *   data: {
   *     // ... data to create a QuestionFigure
   *   }
   * })
   * 
   */
  create<T extends QuestionFigureCreateArgs>(args: Prisma.SelectSubset<T, QuestionFigureCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionFigures.
   * @param {QuestionFigureCreateManyArgs} args - Arguments to create many QuestionFigures.
   * @example
   * // Create many QuestionFigures
   * const questionFigure = await prisma.questionFigure.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionFigureCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionFigureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionFigures and returns the data saved in the database.
   * @param {QuestionFigureCreateManyAndReturnArgs} args - Arguments to create many QuestionFigures.
   * @example
   * // Create many QuestionFigures
   * const questionFigure = await prisma.questionFigure.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionFigures and only return the `id`
   * const questionFigureWithIdOnly = await prisma.questionFigure.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionFigureCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionFigureCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionFigure.
   * @param {QuestionFigureDeleteArgs} args - Arguments to delete one QuestionFigure.
   * @example
   * // Delete one QuestionFigure
   * const QuestionFigure = await prisma.questionFigure.delete({
   *   where: {
   *     // ... filter to delete one QuestionFigure
   *   }
   * })
   * 
   */
  delete<T extends QuestionFigureDeleteArgs>(args: Prisma.SelectSubset<T, QuestionFigureDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionFigure.
   * @param {QuestionFigureUpdateArgs} args - Arguments to update one QuestionFigure.
   * @example
   * // Update one QuestionFigure
   * const questionFigure = await prisma.questionFigure.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionFigureUpdateArgs>(args: Prisma.SelectSubset<T, QuestionFigureUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionFigures.
   * @param {QuestionFigureDeleteManyArgs} args - Arguments to filter QuestionFigures to delete.
   * @example
   * // Delete a few QuestionFigures
   * const { count } = await prisma.questionFigure.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionFigureDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionFigureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionFigures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionFigures
   * const questionFigure = await prisma.questionFigure.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionFigureUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionFigureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionFigures and returns the data updated in the database.
   * @param {QuestionFigureUpdateManyAndReturnArgs} args - Arguments to update many QuestionFigures.
   * @example
   * // Update many QuestionFigures
   * const questionFigure = await prisma.questionFigure.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionFigures and only return the `id`
   * const questionFigureWithIdOnly = await prisma.questionFigure.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionFigureUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionFigureUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionFigure.
   * @param {QuestionFigureUpsertArgs} args - Arguments to update or create a QuestionFigure.
   * @example
   * // Update or create a QuestionFigure
   * const questionFigure = await prisma.questionFigure.upsert({
   *   create: {
   *     // ... data to create a QuestionFigure
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionFigure we want to update
   *   }
   * })
   */
  upsert<T extends QuestionFigureUpsertArgs>(args: Prisma.SelectSubset<T, QuestionFigureUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionFigureClient<runtime.Types.Result.GetResult<Prisma.$QuestionFigurePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionFigures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureCountArgs} args - Arguments to filter QuestionFigures to count.
   * @example
   * // Count the number of QuestionFigures
   * const count = await prisma.questionFigure.count({
   *   where: {
   *     // ... the filter for the QuestionFigures we want to count
   *   }
   * })
  **/
  count<T extends QuestionFigureCountArgs>(
    args?: Prisma.Subset<T, QuestionFigureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionFigureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionFigure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionFigureAggregateArgs>(args: Prisma.Subset<T, QuestionFigureAggregateArgs>): Prisma.PrismaPromise<GetQuestionFigureAggregateType<T>>

  /**
   * Group by QuestionFigure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionFigureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionFigureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionFigureGroupByArgs['orderBy'] }
      : { orderBy?: QuestionFigureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionFigureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionFigureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionFigure model
 */
readonly fields: QuestionFigureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionFigure.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionFigureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  program<T extends Prisma.ProgramDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgramDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgramClient<runtime.Types.Result.GetResult<Prisma.$ProgramPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionFigure model
 */
export interface QuestionFigureFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly programId: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly path: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly fileName: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly svg: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly byteSize: Prisma.FieldRef<"QuestionFigure", 'Int'>
  readonly checksum: Prisma.FieldRef<"QuestionFigure", 'String'>
  readonly createdAt: Prisma.FieldRef<"QuestionFigure", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QuestionFigure", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionFigure findUnique
 */
export type QuestionFigureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter, which QuestionFigure to fetch.
   */
  where: Prisma.QuestionFigureWhereUniqueInput
}

/**
 * QuestionFigure findUniqueOrThrow
 */
export type QuestionFigureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter, which QuestionFigure to fetch.
   */
  where: Prisma.QuestionFigureWhereUniqueInput
}

/**
 * QuestionFigure findFirst
 */
export type QuestionFigureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter, which QuestionFigure to fetch.
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionFigures to fetch.
   */
  orderBy?: Prisma.QuestionFigureOrderByWithRelationInput | Prisma.QuestionFigureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionFigures.
   */
  cursor?: Prisma.QuestionFigureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionFigures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionFigures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionFigures.
   */
  distinct?: Prisma.QuestionFigureScalarFieldEnum | Prisma.QuestionFigureScalarFieldEnum[]
}

/**
 * QuestionFigure findFirstOrThrow
 */
export type QuestionFigureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter, which QuestionFigure to fetch.
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionFigures to fetch.
   */
  orderBy?: Prisma.QuestionFigureOrderByWithRelationInput | Prisma.QuestionFigureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionFigures.
   */
  cursor?: Prisma.QuestionFigureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionFigures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionFigures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionFigures.
   */
  distinct?: Prisma.QuestionFigureScalarFieldEnum | Prisma.QuestionFigureScalarFieldEnum[]
}

/**
 * QuestionFigure findMany
 */
export type QuestionFigureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter, which QuestionFigures to fetch.
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionFigures to fetch.
   */
  orderBy?: Prisma.QuestionFigureOrderByWithRelationInput | Prisma.QuestionFigureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionFigures.
   */
  cursor?: Prisma.QuestionFigureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionFigures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionFigures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionFigures.
   */
  distinct?: Prisma.QuestionFigureScalarFieldEnum | Prisma.QuestionFigureScalarFieldEnum[]
}

/**
 * QuestionFigure create
 */
export type QuestionFigureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionFigure.
   */
  data: Prisma.XOR<Prisma.QuestionFigureCreateInput, Prisma.QuestionFigureUncheckedCreateInput>
}

/**
 * QuestionFigure createMany
 */
export type QuestionFigureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionFigures.
   */
  data: Prisma.QuestionFigureCreateManyInput | Prisma.QuestionFigureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuestionFigure createManyAndReturn
 */
export type QuestionFigureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionFigures.
   */
  data: Prisma.QuestionFigureCreateManyInput | Prisma.QuestionFigureCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionFigure update
 */
export type QuestionFigureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionFigure.
   */
  data: Prisma.XOR<Prisma.QuestionFigureUpdateInput, Prisma.QuestionFigureUncheckedUpdateInput>
  /**
   * Choose, which QuestionFigure to update.
   */
  where: Prisma.QuestionFigureWhereUniqueInput
}

/**
 * QuestionFigure updateMany
 */
export type QuestionFigureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionFigures.
   */
  data: Prisma.XOR<Prisma.QuestionFigureUpdateManyMutationInput, Prisma.QuestionFigureUncheckedUpdateManyInput>
  /**
   * Filter which QuestionFigures to update
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * Limit how many QuestionFigures to update.
   */
  limit?: number
}

/**
 * QuestionFigure updateManyAndReturn
 */
export type QuestionFigureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * The data used to update QuestionFigures.
   */
  data: Prisma.XOR<Prisma.QuestionFigureUpdateManyMutationInput, Prisma.QuestionFigureUncheckedUpdateManyInput>
  /**
   * Filter which QuestionFigures to update
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * Limit how many QuestionFigures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionFigure upsert
 */
export type QuestionFigureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionFigure to update in case it exists.
   */
  where: Prisma.QuestionFigureWhereUniqueInput
  /**
   * In case the QuestionFigure found by the `where` argument doesn't exist, create a new QuestionFigure with this data.
   */
  create: Prisma.XOR<Prisma.QuestionFigureCreateInput, Prisma.QuestionFigureUncheckedCreateInput>
  /**
   * In case the QuestionFigure was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionFigureUpdateInput, Prisma.QuestionFigureUncheckedUpdateInput>
}

/**
 * QuestionFigure delete
 */
export type QuestionFigureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
  /**
   * Filter which QuestionFigure to delete.
   */
  where: Prisma.QuestionFigureWhereUniqueInput
}

/**
 * QuestionFigure deleteMany
 */
export type QuestionFigureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionFigures to delete
   */
  where?: Prisma.QuestionFigureWhereInput
  /**
   * Limit how many QuestionFigures to delete.
   */
  limit?: number
}

/**
 * QuestionFigure without action
 */
export type QuestionFigureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionFigure
   */
  select?: Prisma.QuestionFigureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionFigure
   */
  omit?: Prisma.QuestionFigureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionFigureInclude<ExtArgs> | null
}
