
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Passkey
 * 
 */
export type Passkey = Prisma.PasskeyModel
/**
 * Model Program
 * 
 */
export type Program = Prisma.ProgramModel
/**
 * Model Course
 * 
 */
export type Course = Prisma.CourseModel
/**
 * Model Lesson
 * 
 */
export type Lesson = Prisma.LessonModel
/**
 * Model Exercise
 * 
 */
export type Exercise = Prisma.ExerciseModel
/**
 * Model QuestionChapter
 * 
 */
export type QuestionChapter = Prisma.QuestionChapterModel
/**
 * Model Passage
 * 
 */
export type Passage = Prisma.PassageModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model QuestionOption
 * 
 */
export type QuestionOption = Prisma.QuestionOptionModel
/**
 * Model QuestionFigure
 * 
 */
export type QuestionFigure = Prisma.QuestionFigureModel
/**
 * Model ExerciseQuestion
 * 
 */
export type ExerciseQuestion = Prisma.ExerciseQuestionModel
